/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 12-Jul-2023 15:38:19
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 26
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
unsigned int order_band_FIR = 25;
float b_band_FIR[] = {
                0,0.0004747730272,-0.001864802558,-0.005617362913,-0.003683628514,
   0.003412956605,-0.003118708031, -0.04281681404, -0.09974654019,  -0.1152308136,
   -0.03758207336,   0.1125817597,   0.2380624712,   0.2380624712,   0.1125817597,
   -0.03758207336,  -0.1152308136, -0.09974654019, -0.04281681404,-0.003118708031,
   0.003412956605,-0.003683628514,-0.005617362913,-0.001864802558,0.0004747730272,
                0
};
