/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 12-Jul-2023 15:47:44
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 6
 * Denominator Length  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
unsigned int order_high_IIR = 5;
float b_high_IIR[] = {
     0.1493197978,  -0.7465990186,    1.493198037,   -1.493198037,   0.7465990186,
    -0.1493197978
};

float a_high_IIR[] = {
                1,   -1.479671478,    1.403691769,  -0.6808564067,   0.1918841004,
   -0.02212989703
};
