/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 04-Aug-2023 09:35:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 21
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int order_high_FIR = 21;
const float b_high_FIR[21] = {
   0.002540317131,  0.00164204638,-0.003916098736, -0.01208008546,-0.006506550591,
    0.02424971946,  0.05150184408,  0.01341833174,  -0.1171630919,  -0.2765600085,
     0.6484271288,  -0.2765600085,  -0.1171630919,  0.01341833174,  0.05150184408,
    0.02424971946,-0.006506550591, -0.01208008546,-0.003916098736,  0.00164204638,
   0.002540317131
};
