/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 11-Jul-2023 11:35:59
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
unsigned int order_low_FIR = 30;
float b_low_FIR[]  = {
		  -0.001732726349,-0.001987482887,-0.002421532525,-0.002671134192,-0.002119254088,
		  1.233399602e-18, 0.004438057076,  0.01174226031,  0.02208155021,  0.03512892127,
		     0.0500324741,   0.0654894039,   0.0799158439,  0.09168443829,  0.09938617051,
		     0.1020660102,  0.09938617051,  0.09168443829,   0.0799158439,   0.0654894039,
		     0.0500324741,  0.03512892127,  0.02208155021,  0.01174226031, 0.004438057076,
		  1.233399602e-18,-0.002119254088,-0.002671134192,-0.002421532525,-0.001987482887,
		  -0.001732726349
		};

