/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
 * Generated on: 10-Jul-2023 11:23:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\Polyspace\R2021a\extern\include\tmwtypes.h 
 */
unsigned int order_low_IIR = 5;
 float b_low_IIR[4] = {
   0.002898194361,  0.00869458355,  0.00869458355, 0.002898194361
};

float a_low_IIR[4] = {
                1,   -2.374094725,    1.929355741,  -0.5320753455
};
